### ISSUE TITLE
how can i specify the clentid with regular expressions?Or surport this with extension

### ISSUE THREAD

**Issue by eshxcmhk** [emqtt/emq-auth-clientid#65]

**Comment by hjianbo** [comment]
Hi @eshxcmhk Sorry for so delay replying here.

it's an awesome suggestion, I think. We will discuss it in tomorrow morning's meeting.

**Comment by hjianbo** [comment]
Hi. @eshxcmhk We agree that the emqx_auth_clientid should be a simple keyword authentication, and should not introduce excessive complexity. Moreover, from the perspective of implementation, there will be some problems in the implementation to support multiple regularities

Thanks for your feedback!
